language: go

go:
  - "1.16.x"

go_import_path: github.com/devopsext/sre

before_install:
  - env GO111MODULE=on

install:
  - go get -t -v ./ ./cmd ./common ./provider

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./ ./cmd ./common ./provider
  - go build ./ ./cmd ./common ./provider

after_success:
  - bash <(curl -s https://codecov.io/bash)